In [2]:
import pandas as pd
import numpy as np

In [3]:
#Cleaning up the cells geo dataset
geo = pd.read_csv('cells_geo.csv', index_col = 0)
geo.head()

,VILLES,STATUS,LOCALISATION,DECOUPZONE,ZONENAME,LONGITUDE,LATITUDE,REGION,AREA,CELL_ID,SITE_CODE
0,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,fbb2e75af3,0bb492ef17
1,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,1502501d78,0bb492ef17
2,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,0c2e182a0c,0bb492ef17
3,ASSINIE,In Service,INTERIEUR,Grand-EST,"ASSINIE""",-3.488467,5.158761,SUD COMOE,NaN,69bdfc69fd,8a1e6ce31f
4,ASSINIE,In Service,INTERIEUR,Grand-EST,"ASSINIE""",-3.488467,5.158761,SUD COMOE,NaN,7a1029d2ab,8a1e6ce31f

In [4]:
df = pd.DataFrame(geo)
df.head()

,VILLES,STATUS,LOCALISATION,DECOUPZONE,ZONENAME,LONGITUDE,LATITUDE,REGION,AREA,CELL_ID,SITE_CODE
0,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,fbb2e75af3,0bb492ef17
1,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,1502501d78,0bb492ef17
2,ADJAME,In Service,ABIDJAN,"""Abidjan_EST",AGBANNEW,-4.000667,5.368194,LAGUNE,NaN,0c2e182a0c,0bb492ef17
3,ASSINIE,In Service,INTERIEUR,Grand-EST,"ASSINIE""",-3.488467,5.158761,SUD COMOE,NaN,69bdfc69fd,8a1e6ce31f
4,ASSINIE,In Service,INTERIEUR,Grand-EST,"ASSINIE""",-3.488467,5.158761,SUD COMOE,NaN,7a1029d2ab,8a1e6ce31f

In [5]:
df.shape

(3974, 11)

In [6]:
#converting the column names into lower case
df.columns = map(str.lower, df.columns)
df.columns

Index(['villes', 'status', 'localisation', 'decoupzone', 'zonename',
       'longitude', 'latitude', 'region', 'area', 'cell_id', 'site_code'],
      dtype='object')

In [7]:
#renaming the column names of villes and site id
df.rename(columns = {'villes':'cities','site_code':'site_id'}, inplace = True)
df.columns

Index(['cities', 'status', 'localisation', 'decoupzone', 'zonename',
       'longitude', 'latitude', 'region', 'area', 'cell_id', 'site_id'],
      dtype='object')

In [8]:
df.drop(['decoupzone', 'zonename','longitude', 'latitude', 'area'], axis = 1, inplace = True)
df.head()

    cities      status localisation     region     cell_id     site_id
0   ADJAME  In Service      ABIDJAN     LAGUNE  fbb2e75af3  0bb492ef17
1   ADJAME  In Service      ABIDJAN     LAGUNE  1502501d78  0bb492ef17
2   ADJAME  In Service      ABIDJAN     LAGUNE  0c2e182a0c  0bb492ef17
3  ASSINIE  In Service    INTERIEUR  SUD COMOE  69bdfc69fd  8a1e6ce31f
4  ASSINIE  In Service    INTERIEUR  SUD COMOE  7a1029d2ab  8a1e6ce31f

In [9]:
df.isnull().sum()

cities           0
status          67
localisation     0
region           0
cell_id          0
site_id          0
dtype: int64

In [10]:
df.status.fillna(df.status.mode()[0], inplace = True)
df.isnull().sum()

cities          0
status          0
localisation    0
region          0
cell_id         0
site_id         0
dtype: int64

In [12]:
moringa = pd.read_csv('MoringaSchool_CB_CDR_20120507.csv')
moringa

,PRODUTC,VALUE,DATETIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,Voice,0,2012-05-06 23:04:37.0,1,49fae048b547780,1a49f8b0ded9de6,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu
1,sms,0,2012-05-06 23:05:25.0,0,7a54a6eaee19e65,93343ba6e41af95,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
2,sms,25,2012-05-06 23:05:41.0,0,6008887b0207d82,7aacc9709ce0a20,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
3,Voice,56,2012-05-06 23:05:42.0,1,7370032e20f4e96,6af4a60e74c91d3,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,14,2012-05-06 23:06:29.0,1,966ba4656e38e62,02aa736ee555d5c,19e2e,19e2e,051KhYDCpv,051KhYDCpv
5,data,0,2012-05-06 23:07:26.0,_,f71825ca6e623f9,5a4dc9e82deb309,19e2e,OTHER,/lrUXVGVcN,/lrUXVGVcN
6,Voice,0,2012-05-06 23:08:02.0,1,4afd7d5af21b1ce,67bf1ac30e58e2f,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
7,Voice,0,2012-05-06 23:08:03.0,5,d717dee81c51389,adde5afd9a67b10,19e2e,19e2e,09UjmmY1Ds,09UjmmY1Ds
8,Voice,0,2012-05-06 23:08:05.0,1,44522aefdc918a6,19e68e80103885e,19e2e,19e2e,0DeimCpZOc,0DeimCpZOc
9,sms,0,2012-05-06 23:08:43.0,0,0763a571d24db64,f773694c00c74d2,19e2e,19e2e,01MDiY5F89,01MDiY5F89
10,sms,0,2012-05-06 23:08:50.0,2,93105314189e879,d79384629278326,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
11,sms,0,2012-05-06 23:09:12.0,2,a53686548a74582,d164ed0a0cf2360,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
12,sms,0,2012-05-06 23:09:13.0,1,9938d2d3c72399e,ff0c464449d36fb,19e2e,19e2e,0//cZOoEXj,0//cZOoEXj
13,sms,25,2012-05-06 23:09:16.0,1,225a414d7f66444,4ee1446e20cbc0b,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
14,Voice,0,2012-05-06 23:09:26.0,1,d5b3ec1778ad8c0,cc36f4260f66fee,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
15,Voice,0,2012-05-06 23:09:51.0,0,c34ef4252d76415,73e1048bfe78617,19e2e,19e2e,176sGHv7Ym,176sGHv7Ym
16,Voice,44,2012-05-06 23:09:54.0,2,e708c33795563f1,8f9487c2e6f468e,19e2e,19e2e,++ctND+jGD,++ctND+jGD
17,Voice,0,2012-05-06 23:09:59.0,2,00dcbcd23dc675c,23a453f5189cc79,19e2e,19e2e,1JODMow6DN,1JODMow6DN
18,sms,0,2012-05-06 23:10:05.0,0,8ab8b9ed6989f61,e09e736e46c5c3d,19e2e,19e2e,2PbwFG2K9y,2PbwFG2K9y
19,Voice,14,2012-05-06 23:10:23.0,1,dad978f7b8a9a09,28a6bcdc24a8b38,19e2e,19e2e,2GgIN622rt,2GgIN622rt
20,data,0,2012-05-06 23:10:30.0,_,057c5fb59d8f14f,5a4dc9e82deb309,19e2e,OTHER,/vLAMOS+Qm,/vLAMOS+Qm
21,sms,0,2012-05-06 23:10:41.0,1,c5a7d9300397229,55742f0b8e5b08d,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
22,sms,50,2012-05-06 23:11:14.0,1,8ac7935e68f6ab3,a9e781764b4728a,19e2e,19e2e,2FzOAUm82C,2FzOAUm82C
23,data,0,2012-05-06 23:11:27.0,_,795c2a90bd8d442,5a4dc9e82deb309,19e2e,OTHER,2yuhUrSXQu,2yuhUrSXQu
24,Voice,0,2012-05-06 23:11:27.0,1,1a2b54695968d46,55ad144fa74fddc,19e2e,19e2e,3mQAiRAfo7,3mQAiRAfo7
25,data,0,2012-05-06 23:12:07.0,_,0471428956c85d0,5a4dc9e82deb309,19e2e,OTHER,2FzOAUm82C,2FzOAUm82C
26,Voice,0,2012-05-06 23:12:10.0,2,12c6cf3d45dc493,8f6917492bd38a0,19e2e,19e2e,+gySf02tKW,+gySf02tKW
27,Voice,19,2012-05-06 23:12:25.0,0,b0ffeee6fe3c759,3f830c98519c5e9,19e2e,19e2e,/EkqCbWDau,/EkqCbWDau
28,sms,25,2012-05-06 23:12:25.0,0,21939efec26bf4e,ba7e17ea91737fa,19e2e,19e2e,/kxqxDGV0Z,/kxqxDGV0Z
29,sms,0,2012-05-06 23:12:36.0,2,1e9789aacb2b6dd,93343ba6e41af95,19e2e,19e2e,4K++Px614U,4K++Px614U
...,...,...,...,...,...,...,...,...,...,...
15011786,sms,25,2012-05-08 00:48:03.0,2,9a5d17a904cb47a,70fa6582119c62d,19e2e,19e2e,z5bs3CFOnv,z5bs3CFOnv
15011787,Voice,60,2012-05-08 00:48:36.0,2,ba9095bd3fb1f73,9d135fb3b7df8ac,19e2e,19e2e,vflQKK8iw1,vflQKK8iw1
15011788,sms,0,2012-05-08 00:49:04.0,0,ed9ae010ef56b2e,6ad6460e07c9f4d,19e2e,19e2e,uAoxY8YwfC,uAoxY8YwfC
15011789,Voice,20,2012-05-08 00:49:24.0,4,32657d4ce62ea6d,de772504f906252,19e2e,19e2e,yhTF197Bj3,yhTF197Bj3
15011790,sms,0,2012-05-08 00:49:26.0,4,483773410aa8d98,aaaf0e4bdec7311,19e2e,19e2e,vlMkDkX66e,vlMkDkX66e
15011791,sms,0,2012-05-08 00:49:32.0,2,d37759db0fb00d1,4c304886fd0be3f,19e2e,19e2e,uerZrkyQPN,uerZrkyQPN
15011792,Voice,30,2012-05-08 00:49:42.0,4,b74760728a296d6,b10cc5c87f0cc36,19e2e,19e2e,vrROenKiJT,vrROenKiJT
15011793,sms,0,2012-05-08 00:49:44.0,1,5f541a3cd639f7a,106a3a1384202bd,19e2e,19e2e,zn4qbCp2XH,zn4qbCp2XH
15011794,Voice,30,2012-05-08 00:50:11.0,0,150123ab83ead1f,ae76300252f84bf,19e2e,19e2e,yFXPYvL+xd,yFXPYvL+xd
15011795,sms,0,2012-05-08 00:50:18.0,2,cfdc50f4b5b0725,5a658746e3e8ea0,19e2e,19e2e,y+XgMoAQCw,y+XgMoAQCw
15011796,sms,0,2012-05-08 00:50:33.0,3,14914fde7b3198d,aba4af92c44fd2e,19e2e,19e2e,wo9VXaAbwE,wo9VXaAbwE
15011797,sms,0,2012-05-08 00:50:51.0,5,46813e86e96bff5,9abb77b298ec1d6,19e2e,19e2e,zIzAzjMShv,zIzAzjMShv
15011798,sms,0,2012-05-08 00:50:59.0,3,cd80e40e4695dd8,93343ba6e41af95,19e2e,19e2e,zbVRn1hiwe,zbVRn1hiwe
15011799,sms,0,2012-05-08 00:51:07.0,2,4d10ec3ad006208,34a5079552970ae,19e2e,19e2e,wSRV7UPBqf,wSRV7UPBqf
15011800,sms,0,2012-05-08 00:51:07.0,2,cd3ce804156928b,4b96df025dbdb5a,19e2e,19e2e,yKiIEdEjU5,yKiIEdEjU5
15011801,sms,0,2012-05-08 00:51:19.0,1,d2a9c5d2033d5f0,cd46f952aafe6e5,19e2e,19e2e,yruj+VWDJ8,yruj+VWDJ8
15011802,sms,0,2012-05-08 00:51:28.0,0,e9c0274d885506a,93343ba6e41af95,19e2e,19e2e,zn4qbCp2XH,zn4qbCp2XH
15011803,Voice,6,2012-05-08 00:52:15.0,3,a942e9ca45fe4ef,ffb6dada42aa3fa,19e2e,19e2e,yNqhpwnhny,yNqhpwnhny
15011804,sms,0,2012-05-08 00:52:21.0,2,6a036ab30b3aca4,7af76c2046e02f3,19e2e,OTHER,zsA2dnzCR5,zsA2dnzCR5
15011805,sms,25,2012-05-08 00:53:12.0,2,99034d39da0be34,2c1d7470bce4a37,19e2e,19e2e,wmgg5EbE9n,wmgg5EbE9n
15011806,Voice,3,2012-05-08 00:53:29.0,0,7623de684da719c,4ec907ddf4b0f83,19e2e,19e2e,yyGsWkQmCT,yyGsWkQmCT
15011807,sms,0,2012-05-08 00:53:51.0,0,944b3615c165367,be815fb0a7a351e,19e2e,19e2e,yhTF197Bj3,yhTF197Bj3
15011808,sms,0,2012-05-08 00:54:00.0,0,84eb93e66cc1c43,f9e8ee791b5c09b,19e2e,19e2e,yyGsWkQmCT,yyGsWkQmCT
15011809,data,0,2012-05-08 00:54:10.0,_,54d52aa85affec2,5a4dc9e82deb309,19e2e,OTHER,yKiIEdEjU5,yKiIEdEjU5
15011810,sms,0,2012-05-08 00:55:40.0,0,aed59daa5ee6a46,63049f14a890910,19e2e,19e2e,zsA2dnzCR5,zsA2dnzCR5
15011811,Voice,40,2012-05-08 00:56:07.0,0,e987bf660f247dc,063cac5c0732e0e,19e2e,19e2e,y8Zy+A5U3K,y8Zy+A5U3K
15011812,sms,0,2012-05-08 00:56:17.0,2,b8c272a0f3af025,0330e9891becf50,19e2e,19e2e,yGAZ0YDzFi,yGAZ0YDzFi
15011813,sms,0,2012-05-08 00:57:49.0,4,444da5f3bc97ddd,cdf059592911590,19e2e,19e2e,ywp1Gp+dk/,ywp1Gp+dk/
15011814,sms,0,2012-05-08 00:57:51.0,2,4e74f5fb77a9626,403d3a68252a05b,19e2e,19e2e,zsA2dnzCR5,zsA2dnzCR5
15011815,sms,0,2012-05-08 00:59:05.0,4,483773410aa8d98,aaaf0e4bdec7311,19e2e,19e2e,zn4qbCp2XH,zn4qbCp2XH

In [13]:
df1 = pd.DataFrame(moringa)
df1.head()

,PRODUTC,VALUE,DATETIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,Voice,0,2012-05-06 23:04:37.0,1,49fae048b547780,1a49f8b0ded9de6,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu
1,sms,0,2012-05-06 23:05:25.0,0,7a54a6eaee19e65,93343ba6e41af95,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
2,sms,25,2012-05-06 23:05:41.0,0,6008887b0207d82,7aacc9709ce0a20,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
3,Voice,56,2012-05-06 23:05:42.0,1,7370032e20f4e96,6af4a60e74c91d3,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,14,2012-05-06 23:06:29.0,1,966ba4656e38e62,02aa736ee555d5c,19e2e,19e2e,051KhYDCpv,051KhYDCpv

In [14]:
df1.columns = map(str.lower, df1.columns)
df1.columns

Index(['produtc', 'value', 'datetime', 'cell_on_site', 'dw_a_number_int',
       'dw_b_number_int', 'country_a', 'country_b', 'cell_id', 'site_id'],
      dtype='object')

In [15]:
df1.shape

(15011816, 10)

In [16]:
df1.rename(columns={'produtc':'product', 'datetime':'date_time'}, inplace = True)

In [17]:
df1.columns

Index(['product', 'value', 'date_time', 'cell_on_site', 'dw_a_number_int',
       'dw_b_number_int', 'country_a', 'country_b', 'cell_id', 'site_id'],
      dtype='object')

In [18]:
df1.drop(['cell_on_site','dw_a_number_int','dw_b_number_int','country_a','country_b'], axis = 1, inplace = True)
df1.head()

  product  value              date_time     cell_id     site_id
0   Voice      0  2012-05-06 23:04:37.0  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  /u0FSD+ahi  /u0FSD+ahi
3   Voice     56  2012-05-06 23:05:42.0  +cNeJzsTp3  +cNeJzsTp3
4   Voice     14  2012-05-06 23:06:29.0  051KhYDCpv  051KhYDCpv

In [19]:
df1.isnull().sum()

product           0
value             0
date_time         0
cell_id           0
site_id      540033
dtype: int64

In [20]:
df1.site_id.fillna(df.site_id.mode()[0], inplace = True)
df1.isnull().sum()

product      0
value        0
date_time    0
cell_id      0
site_id      0
dtype: int64

In [22]:
moringa2 = pd.read_csv('MoringaSchool_CB_CDR_20120508.csv')
moringa2

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER,DW_B_NUMBER,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,sms,0,2012-05-07 23:02:06.0,2,32255675c3b6fe3,1aa7ae01386e9fb,19e2e,19e2e,+854AcBQT2,+854AcBQT2
1,Voice,0,2012-05-07 23:03:44.0,1,ff16d6ac74c1c64,87d87309c15a8c9,19e2e,19e2e,+854AcBQT2,+854AcBQT2
2,sms,0,2012-05-07 23:04:06.0,0,98d9f2fb5ff624b,93343ba6e41af95,19e2e,19e2e,+laSrk7g6q,+laSrk7g6q
3,Voice,37,2012-05-07 23:04:48.0,1,3f9c8a33ec7be1f,7d05a38f89c49d8,19e2e,19e2e,/xvRrCVKoQ,/xvRrCVKoQ
4,sms,25,2012-05-07 23:04:58.0,1,7bcccc03adf3864,56a5d5430d2fa86,19e2e,19e2e,+bO+qkSonO,+bO+qkSonO
5,sms,0,2012-05-07 23:05:41.0,4,d73f11fdc9fcb30,ec90fdb12b50cbc,19e2e,19e2e,/MMplBlWjh,/MMplBlWjh
6,Voice,41,2012-05-07 23:06:14.0,1,eafaf521153b405,70a60b7bca83a58,19e2e,19e2e,+laSrk7g6q,+laSrk7g6q
7,Voice,11,2012-05-07 23:06:28.0,0,a1799cdc5108a90,efee282793c4e56,19e2e,19e2e,+gySf02tKW,+gySf02tKW
8,sms,0,2012-05-07 23:06:35.0,2,f81bb99db8c0373,7af76c2046e02f3,19e2e,OTHER,/0FxP3az1x,/0FxP3az1x
9,sms,0,2012-05-07 23:06:50.0,0,6a7d89469dc20e9,3690c6c0444c0c0,19e2e,19e2e,0ecjmwPX21,0ecjmwPX21
10,sms,0,2012-05-07 23:06:58.0,0,81dff572800e83b,032780927a1a585,19e2e,19e2e,+laSrk7g6q,+laSrk7g6q
11,sms,0,2012-05-07 23:06:58.0,4,58ba5cac616c660,eae5d7838a2c2af,19e2e,19e2e,/MMplBlWjh,/MMplBlWjh
12,sms,0,2012-05-07 23:07:02.0,0,1aa429cb0ad4fff,e3bef4a57aef283,19e2e,19e2e,+YzQI97cPp,+YzQI97cPp
13,sms,0,2012-05-07 23:07:03.0,2,b180d01b4646ef3,ca694e0ede22e5d,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
14,sms,0,2012-05-07 23:07:23.0,1,53b723717713150,e09e736e46c5c3d,19e2e,19e2e,0BRdojv2my,0BRdojv2my
15,sms,0,2012-05-07 23:07:51.0,2,b180d01b4646ef3,d61935085e1f8eb,19e2e,19e2e,+e+xcimwre,+e+xcimwre
16,sms,0,2012-05-07 23:08:09.0,0,5ab4a54a9b7fec5,77e60ff7b25ba51,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
17,sms,25,2012-05-07 23:08:14.0,0,f068be3c70ed1ff,f6c86a6ab602a4e,19e2e,19e2e,+gQ2AvXjaO,+gQ2AvXjaO
18,Voice,0,2012-05-07 23:08:16.0,1,9dec957084f076d,19e68e80103885e,19e2e,19e2e,/0LopuZdd7,/0LopuZdd7
19,sms,0,2012-05-07 23:08:32.0,1,f76dbe9dfd7eaa4,d92f6918d687f52,19e2e,19e2e,0BRdojv2my,0BRdojv2my
20,data,0,2012-05-07 23:08:53.0,_,be670b7d317c859,5a4dc9e82deb309,19e2e,OTHER,/0FxP3az1x,/0FxP3az1x
21,sms,0,2012-05-07 23:09:33.0,1,ef1a358db9a72e2,43e8ef31c7490e8,19e2e,19e2e,+pZNtCvhmT,+pZNtCvhmT
22,Voice,0,2012-05-07 23:09:45.0,2,bb0758afdc08f2d,99fac14d328d914,19e2e,19e2e,+YzQI97cPp,+YzQI97cPp
23,sms,0,2012-05-07 23:09:50.0,1,8da7870ee027a39,43856ca73fbadf3,19e2e,19e2e,+854AcBQT2,+854AcBQT2
24,sms,0,2012-05-07 23:09:56.0,1,0108b4b998a2041,8051dc22ab2d575,19e2e,19e2e,+e+xcimwre,+e+xcimwre
25,Voice,0,2012-05-07 23:10:13.0,0,eece320c922fa19,f9f0526aca7ba01,19e2e,19e2e,+pZNtCvhmT,+pZNtCvhmT
26,sms,0,2012-05-07 23:10:36.0,0,c731afd285c9261,77707f4a0b2b068,19e2e,19e2e,2aXXOLyR5M,2aXXOLyR5M
27,sms,0,2012-05-07 23:10:37.0,1,a7a86b45f71c7e8,eb6a23422ba7b5b,19e2e,19e2e,0r4EVaG2A/,0r4EVaG2A/
28,sms,0,2012-05-07 23:11:45.0,0,d114ab1c07a5c52,1cd0cede39e2daa,19e2e,19e2e,/xvRrCVKoQ,/xvRrCVKoQ
29,Voice,0,2012-05-07 23:11:50.0,3,5d16e0ca3d52c0f,1ffdd0f01418825,19e2e,19e2e,1BFUFggilV,1BFUFggilV
...,...,...,...,...,...,...,...,...,...,...
19606082,sms,0,2012-05-09 00:52:32.0,1,2f91b73d6207a13,0ef3e151f7b0d62,19e2e,19e2e,yXO/but0cw,yXO/but0cw
19606083,sms,25,2012-05-09 00:52:49.0,0,a259b0cc638a478,f3234181d138af4,19e2e,19e2e,vrROenKiJT,vrROenKiJT
19606084,sms,0,2012-05-09 00:52:55.0,1,25aa14ec9036b16,e51d70429028328,19e2e,19e2e,yPq8TPd7WC,yPq8TPd7WC
19606085,sms,0,2012-05-09 00:53:03.0,0,fb9e9275bf6682d,fbe8a95497ab38e,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc
19606086,sms,0,2012-05-09 00:53:05.0,1,a29500aab5824c2,67c3febe9f32abc,19e2e,19e2e,yKiIEdEjU5,yKiIEdEjU5
19606087,sms,0,2012-05-09 00:53:07.0,1,1cd3b8e90ed7e2a,099959d4d4a33bd,19e2e,19e2e,zyYNfma31d,zyYNfma31d
19606088,Voice,196,2012-05-09 00:53:19.0,1,210eaf04e0d81bf,ee640a6183fd1f0,19e2e,19e2e,x7bXnQF6F8,x7bXnQF6F8
19606089,sms,0,2012-05-09 00:53:26.0,5,829713c3a1760a4,9b4a2be052f0d75,19e2e,19e2e,z5bs3CFOnv,z5bs3CFOnv
19606090,Voice,173,2012-05-09 00:53:34.0,0,84d115eedd5b7b3,97cb4f1ccd1dc83,19e2e,19e2e,yaDPP9L0Ep,yaDPP9L0Ep
19606091,sms,0,2012-05-09 00:53:43.0,2,ef6c40be335c22e,e22a795f666ce5c,19e2e,19e2e,y+XgMoAQCw,y+XgMoAQCw
19606092,sms,0,2012-05-09 00:53:51.0,0,4a03b02c67508ab,2082dad57458098,19e2e,19e2e,yAbmlrSi3/,yAbmlrSi3/
19606093,sms,0,2012-05-09 00:53:57.0,1,f2040c9ec35e083,c92b101c821de4c,19e2e,19e2e,yXO/but0cw,yXO/but0cw
19606094,sms,0,2012-05-09 00:54:22.0,0,80342f0a2120ce1,3c9a95bc5a3dd74,19e2e,19e2e,wo9VXaAbwE,wo9VXaAbwE
19606095,Voice,60,2012-05-09 00:54:32.0,1,23aa4cf14f253eb,a5300a69da2aff9,19e2e,19e2e,y+XgMoAQCw,y+XgMoAQCw
19606096,sms,0,2012-05-09 00:54:34.0,0,a29d9a0fe11178c,23bfb85103114e4,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc
19606097,sms,0,2012-05-09 00:54:36.0,1,f5d26c16899145a,1203b64eef941aa,19e2e,19e2e,z7ZdRZQCEe,z7ZdRZQCEe
19606098,sms,0,2012-05-09 00:54:38.0,0,38d07ab73998548,28582a3c961cfbf,19e2e,19e2e,xqKepCu/mP,xqKepCu/mP
19606099,Voice,26,2012-05-09 00:54:43.0,0,3d167c4e3828dd7,720641f68979bc0,19e2e,19e2e,zdfL0rhEcy,zdfL0rhEcy
19606100,sms,0,2012-05-09 00:54:44.0,2,48558a39bf1b980,9d000c4ab6f7283,19e2e,19e2e,zbVRn1hiwe,zbVRn1hiwe
19606101,data,0,2012-05-09 00:54:54.0,_,57ec1f05b657784,5a4dc9e82deb309,19e2e,OTHER,z7ZdRZQCEe,z7ZdRZQCEe
19606102,Voice,63,2012-05-09 00:54:55.0,0,50fe39654cbf404,eb00dc77398de10,19e2e,19e2e,zsA2dnzCR5,zsA2dnzCR5
19606103,sms,0,2012-05-09 00:54:58.0,0,3753cf210713f86,03b82348a40ed9c,19e2e,19e2e,zdfL0rhEcy,zdfL0rhEcy
19606104,sms,0,2012-05-09 00:55:58.0,1,efafb8d09366878,e09e736e46c5c3d,19e2e,19e2e,yhTF197Bj3,yhTF197Bj3
19606105,sms,0,2012-05-09 00:56:42.0,1,7004c5e9dc79e0d,5e4173db5ac542c,19e2e,19e2e,zcj81as8v9,zcj81as8v9
19606106,sms,0,2012-05-09 00:56:42.0,2,ef96717559b33f9,a1899c534891b4b,19e2e,19e2e,zsA2dnzCR5,zsA2dnzCR5
19606107,sms,0,2012-05-09 00:57:19.0,0,8a2cb692ebe1d25,025dbecb39a8449,19e2e,19e2e,z34dRyOVua,z34dRyOVua
19606108,sms,0,2012-05-09 00:57:42.0,2,1168882fca2a411,b3d036695a36bac,19e2e,19e2e,zbVRn1hiwe,zbVRn1hiwe
19606109,data,0,2012-05-09 00:58:02.0,_,30d65b6323b5c44,5a4dc9e82deb309,19e2e,OTHER,zIzAzjMShv,zIzAzjMShv
19606110,Voice,101,2012-05-09 00:58:14.0,0,a8ef67453766c7f,5c4e5e5a59f9351,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc
19606111,sms,0,2012-05-09 00:59:05.0,0,894c12654217230,aaaf0e4bdec7311,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc

In [23]:
df2 = pd.DataFrame(moringa2)
df2.head()

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER,DW_B_NUMBER,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,sms,0,2012-05-07 23:02:06.0,2,32255675c3b6fe3,1aa7ae01386e9fb,19e2e,19e2e,+854AcBQT2,+854AcBQT2
1,Voice,0,2012-05-07 23:03:44.0,1,ff16d6ac74c1c64,87d87309c15a8c9,19e2e,19e2e,+854AcBQT2,+854AcBQT2
2,sms,0,2012-05-07 23:04:06.0,0,98d9f2fb5ff624b,93343ba6e41af95,19e2e,19e2e,+laSrk7g6q,+laSrk7g6q
3,Voice,37,2012-05-07 23:04:48.0,1,3f9c8a33ec7be1f,7d05a38f89c49d8,19e2e,19e2e,/xvRrCVKoQ,/xvRrCVKoQ
4,sms,25,2012-05-07 23:04:58.0,1,7bcccc03adf3864,56a5d5430d2fa86,19e2e,19e2e,+bO+qkSonO,+bO+qkSonO

In [24]:
df2.shape

(19606112, 10)

In [25]:
df2.columns = map(str.lower, df2.columns)
df2.columns

Index(['product', 'value', 'date_time', 'cell_on_site', 'dw_a_number',
       'dw_b_number', 'country_a', 'country_b', 'cell_id', 'site_id'],
      dtype='object')

In [26]:
df2.drop(['cell_on_site','dw_a_number','dw_b_number','country_a','country_b'], axis = 1, inplace = True)
df2.head()

  product  value              date_time     cell_id     site_id
0     sms      0  2012-05-07 23:02:06.0  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  +laSrk7g6q  +laSrk7g6q
3   Voice     37  2012-05-07 23:04:48.0  /xvRrCVKoQ  /xvRrCVKoQ
4     sms     25  2012-05-07 23:04:58.0  +bO+qkSonO  +bO+qkSonO

In [27]:
df2.isnull().sum()

product           0
value             0
date_time         0
cell_id           0
site_id      521178
dtype: int64

In [28]:
df2.site_id.fillna(df.site_id.mode()[0], inplace = True)
df2.isnull().sum()

product      0
value        0
date_time    0
cell_id      0
site_id      0
dtype: int64

In [28]:
moringa3 = pd.read_csv('MoringaSchool_CB_CDR_20120509.csv')
moringa3

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELLID,SIET_ID
0,Voice,61,2012-05-08 23:01:28.0,2,966f68353622feb,ffd53a3bb2db6f1,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
1,sms,0,2012-05-08 23:01:31.0,1,a0a597384c612d7,cf3b218f1dde792,19e2e,19e2e,+Fs4mTvdKx,+Fs4mTvdKx
2,Voice,10,2012-05-08 23:02:59.0,1,5441a9a58c97132,52f8b299515b9b7,19e2e,19e2e,+ZaaZozy/+,+ZaaZozy/+
3,sms,0,2012-05-08 23:03:04.0,0,8ab8b9ed6989f61,e09e736e46c5c3d,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,22,2012-05-08 23:03:16.0,4,52662a62b199334,2186273faab4602,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA
5,Voice,10,2012-05-08 23:03:59.0,0,c572f692ed9d25f,5e6221fa6b35f62,19e2e,19e2e,+e+xcimwre,+e+xcimwre
6,sms,0,2012-05-08 23:06:06.0,0,32cc9a0c68cc9ee,9eb1b241c685914,19e2e,19e2e,+R5ccmtyJf,+R5ccmtyJf
7,Voice,10,2012-05-08 23:06:55.0,1,38c234bf93b3aac,ae0bd079dc09dd5,19e2e,19e2e,+ZaaZozy/+,+ZaaZozy/+
8,sms,25,2012-05-08 23:07:09.0,1,6dd0d088cceca75,9bdc6a2acd8ee15,19e2e,19e2e,13O1+JEun3,13O1+JEun3
9,sms,0,2012-05-08 23:07:38.0,0,9572b11240ca426,64898ae3aa9cc93,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA
10,sms,0,2012-05-08 23:07:43.0,2,5b6f26b5d0758fe,e284afced19fcba,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA
11,sms,0,2012-05-08 23:07:55.0,1,8ede080e807c19b,99cbdaebbf97601,19e2e,19e2e,/NPTR0H+5I,/NPTR0H+5I
12,sms,0,2012-05-08 23:08:15.0,1,e4c5f1c8cd08e8a,c8aec3bdc60c6b7,19e2e,19e2e,18MlD9e2CO,18MlD9e2CO
13,sms,0,2012-05-08 23:08:19.0,2,c818e66646d3741,5f6f78591ee8c25,19e2e,19e2e,0K+IDi1yjl,0K+IDi1yjl
14,sms,0,2012-05-08 23:08:24.0,2,d9143fbd9fec15e,ab53f3798c56300,19e2e,19e2e,2GgIN622rt,2GgIN622rt
15,sms,50,2012-05-08 23:08:49.0,0,e8499ca70ff0059,5c248c52e7b272c,19e2e,19e2e,051KhYDCpv,051KhYDCpv
16,Voice,14,2012-05-08 23:09:03.0,2,2e54b715c9a7b7b,93205049fc294cb,19e2e,19e2e,2aXXOLyR5M,2aXXOLyR5M
17,Voice,0,2012-05-08 23:09:04.0,1,3200ab4f46e8316,bd7a1e8a98a0f1b,19e2e,19e2e,/lW1z7T9L8,/lW1z7T9L8
18,data,0,2012-05-08 23:09:24.0,_,30c877b2339ce47,5a4dc9e82deb309,19e2e,OTHER,/EkqCbWDau,/EkqCbWDau
19,data,1,2012-05-08 23:09:35.0,_,934a567b28e381d,5a4dc9e82deb309,19e2e,OTHER,/0FxP3az1x,/0FxP3az1x
20,Voice,6,2012-05-08 23:09:40.0,0,b2638d03948d9cd,b0166164f948347,19e2e,19e2e,0eA3S0GqHt,0eA3S0GqHt
21,data,0,2012-05-08 23:09:43.0,_,46675d106ee0aff,5a4dc9e82deb309,19e2e,OTHER,/0LopuZdd7,/0LopuZdd7
22,sms,0,2012-05-08 23:09:47.0,1,f3b6ba06e9439d8,8e3705f683cfa61,19e2e,19e2e,0UFkHqX87G,0UFkHqX87G
23,sms,25,2012-05-08 23:09:48.0,2,711a413770e5028,fc1e25118646138,19e2e,19e2e,2q0YsSCxbH,2q0YsSCxbH
24,sms,0,2012-05-08 23:10:16.0,4,909bb6ebfb75709,93343ba6e41af95,19e2e,19e2e,1MTLUFpdzd,1MTLUFpdzd
25,Voice,0,2012-05-08 23:10:18.0,0,4541ae20049f39f,553e15a3a1cf612,19e2e,19e2e,0/eYPFomxx,0/eYPFomxx
26,sms,25,2012-05-08 23:10:19.0,0,a18d529f0474619,ce00ff03fd8bc42,19e2e,19e2e,++ctND+jGD,++ctND+jGD
27,data,1,2012-05-08 23:10:20.0,_,2b7b26c7f12113e,5a4dc9e82deb309,19e2e,OTHER,++ctND+jGD,++ctND+jGD
28,sms,0,2012-05-08 23:10:58.0,0,767378197ecc5e5,8fe615f72c53ec5,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu
29,Voice,0,2012-05-08 23:11:04.0,1,096b0934058f8e8,a6b8658a978e68e,19e2e,19e2e,18iJZATMMC,18iJZATMMC
...,...,...,...,...,...,...,...,...,...,...
14834771,sms,0,2012-05-10 00:50:26.0,3,dbf65c28345f89e,21da545616603a4,19e2e,19e2e,wmgg5EbE9n,wmgg5EbE9n
14834772,sms,0,2012-05-10 00:50:28.0,2,d066917479efdbc,f0c2ce0c92e2f03,19e2e,19e2e,vZrfcgHa81,vZrfcgHa81
14834773,sms,0,2012-05-10 00:50:37.0,3,fa3c2365b38f222,3691393288d3c10,19e2e,19e2e,yyGsWkQmCT,yyGsWkQmCT
14834774,data,0,2012-05-10 00:50:39.0,_,182833e7c160186,5a4dc9e82deb309,19e2e,OTHER,zyYNfma31d,zyYNfma31d
14834775,sms,0,2012-05-10 00:50:43.0,1,f1bff6189a27638,549038216f057e0,19e2e,19e2e,vDrYzb5siB,vDrYzb5siB
14834776,sms,0,2012-05-10 00:50:57.0,1,51453d520fa5a40,3b54151fca5675a,19e2e,19e2e,vlMkDkX66e,vlMkDkX66e
14834777,sms,0,2012-05-10 00:50:57.0,2,5129464cc424a3d,485fb70b6902601,19e2e,19e2e,xj8BSS8pPu,xj8BSS8pPu
14834778,sms,0,2012-05-10 00:51:04.0,2,938dc8adbc9d272,aaaf0e4bdec7311,19e2e,19e2e,ywp1Gp+dk/,ywp1Gp+dk/
14834779,Voice,84,2012-05-10 00:51:12.0,2,7f52011bce8b1a8,22e02a2e8fa54de,19e2e,19e2e,vWGjxf3sVb,vWGjxf3sVb
14834780,sms,25,2012-05-10 00:51:40.0,5,106c81bc5cea45d,2beafd4d8db47c6,19e2e,19e2e,w3U/knMGad,w3U/knMGad
14834781,sms,0,2012-05-10 00:51:54.0,2,e39a15df91185e3,aaaf0e4bdec7311,19e2e,19e2e,yFXPYvL+xd,yFXPYvL+xd
14834782,sms,0,2012-05-10 00:52:04.0,1,08fddd51db76d70,2264a3b4fc54d4c,19e2e,19e2e,yGAZ0YDzFi,yGAZ0YDzFi
14834783,sms,0,2012-05-10 00:52:23.0,2,dbe478cf7838000,d6685085d11b8ef,19e2e,19e2e,wSRV7UPBqf,wSRV7UPBqf
14834784,Voice,24,2012-05-10 00:52:28.0,4,221f52534cb8224,859177224287a8d,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc
14834785,Voice,68,2012-05-10 00:52:34.0,0,0b718ed8057aa70,1caf1947393e233,19e2e,19e2e,xj10st71q2,xj10st71q2
14834786,sms,0,2012-05-10 00:52:38.0,2,b7027f13d140682,8b6c3ba92845701,19e2e,19e2e,w/YvPzgPwa,w/YvPzgPwa
14834787,sms,0,2012-05-10 00:52:58.0,2,e0a168890ba64a7,4716522b9ed3357,19e2e,19e2e,zIzAzjMShv,zIzAzjMShv
14834788,Voice,0,2012-05-10 00:53:01.0,1,ae1cf040372bb37,1a49f8b0ded9de6,19e2e,19e2e,ywp1Gp+dk/,ywp1Gp+dk/
14834789,data,0,2012-05-10 00:53:01.0,_,8c91e52d508d764,5a4dc9e82deb309,19e2e,OTHER,zn4qbCp2XH,zn4qbCp2XH
14834790,sms,0,2012-05-10 00:53:06.0,0,d58940f79474aa8,757735824f0312a,19e2e,19e2e,wo9VXaAbwE,wo9VXaAbwE
14834791,Voice,33,2012-05-10 00:53:21.0,1,05811c05a817b10,04f5158317180f8,19e2e,19e2e,xj10st71q2,xj10st71q2
14834792,sms,0,2012-05-10 00:53:33.0,1,fd3562926fb6d07,0c816dfc70b4a9e,19e2e,19e2e,xqKepCu/mP,xqKepCu/mP
14834793,sms,0,2012-05-10 00:53:54.0,1,e409fcb5b3a8269,ef5362fa970b643,19e2e,19e2e,yf1PVM0Ir0,yf1PVM0Ir0
14834794,sms,50,2012-05-10 00:53:54.0,1,29e8b3c3bde0a89,478094e5f25b5ba,19e2e,19e2e,zcj81as8v9,zcj81as8v9
14834795,sms,0,2012-05-10 00:54:14.0,1,8aaae668d99029c,454759c6723a87e,19e2e,19e2e,wyCwF9ZnJm,wyCwF9ZnJm
14834796,Voice,14,2012-05-10 00:55:42.0,2,b06224c153dee8d,4d1a8af24ea36d5,19e2e,19e2e,zsA2dnzCR5,zsA2dnzCR5
14834797,sms,0,2012-05-10 00:55:51.0,2,e350a3354469710,0fdbd19a0598f60,19e2e,19e2e,xxbbz32oIL,xxbbz32oIL
14834798,sms,0,2012-05-10 00:55:53.0,1,20d4e82af4c2e37,f29aa856dc3a8ef,19e2e,19e2e,zbVRn1hiwe,zbVRn1hiwe
14834799,sms,25,2012-05-10 00:57:11.0,1,22a9b87e67cd331,d91e5f4fcf14297,19e2e,19e2e,yPq8TPd7WC,yPq8TPd7WC
14834800,sms,0,2012-05-10 00:59:04.0,2,9425175f71f05d9,bfdd4b8e596ef48,19e2e,19e2e,zqHx55Evcc,zqHx55Evcc

In [29]:
df3 = pd.DataFrame(moringa3)
df3.head()

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELLID,SIET_ID
0,Voice,61,2012-05-08 23:01:28.0,2,966f68353622feb,ffd53a3bb2db6f1,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
1,sms,0,2012-05-08 23:01:31.0,1,a0a597384c612d7,cf3b218f1dde792,19e2e,19e2e,+Fs4mTvdKx,+Fs4mTvdKx
2,Voice,10,2012-05-08 23:02:59.0,1,5441a9a58c97132,52f8b299515b9b7,19e2e,19e2e,+ZaaZozy/+,+ZaaZozy/+
3,sms,0,2012-05-08 23:03:04.0,0,8ab8b9ed6989f61,e09e736e46c5c3d,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,22,2012-05-08 23:03:16.0,4,52662a62b199334,2186273faab4602,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA

In [30]:
df3.shape

(14834801, 10)

In [31]:
df3.columns = map(str.lower, df3.columns)
df3.columns

Index(['product', 'value', 'date_time', 'cell_on_site', 'dw_a_number_int',
       'dw_b_number_int', 'country_a', 'country_b', 'cellid', 'siet_id'],
      dtype='object')

In [32]:
df3.rename(columns={'cellid':'cell_id', 'siet_id':'site_id'}, inplace = True)
df3.columns

Index(['product', 'value', 'date_time', 'cell_on_site', 'dw_a_number_int',
       'dw_b_number_int', 'country_a', 'country_b', 'cell_id', 'site_id'],
      dtype='object')

In [33]:
df3.drop(['cell_on_site','dw_a_number_int','dw_b_number_int','country_a','country_b'], axis = 1, inplace = True)
df3.head()

  product  value              date_time     cell_id     site_id
0   Voice     61  2012-05-08 23:01:28.0  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  +ZaaZozy/+  +ZaaZozy/+
3     sms      0  2012-05-08 23:03:04.0  +cNeJzsTp3  +cNeJzsTp3
4   Voice     22  2012-05-08 23:03:16.0  /eeMklgyJA  /eeMklgyJA

In [34]:
df3.isnull().sum()

product           0
value             0
date_time         0
cell_id           0
site_id      558367
dtype: int64

In [35]:
df3.site_id.fillna(df.site_id.mode()[0], inplace = True)
df3.isnull().sum()

product      0
value        0
date_time    0
cell_id      0
site_id      0
dtype: int64

In [36]:
#concating the three datasets,Moringa 1,Moringa 2,Moringa3
moringas = pd.concat([df1,df2,df3], ignore_index = True, sort = True)
moringas.tail(10)

             cell_id              date_time product     site_id  value
49452719  xj10st71q2  2012-05-10 00:53:21.0   Voice  xj10st71q2     33
49452720  xqKepCu/mP  2012-05-10 00:53:33.0     sms  xqKepCu/mP      0
49452721  yf1PVM0Ir0  2012-05-10 00:53:54.0     sms  yf1PVM0Ir0      0
49452722  zcj81as8v9  2012-05-10 00:53:54.0     sms  zcj81as8v9     50
49452723  wyCwF9ZnJm  2012-05-10 00:54:14.0     sms  wyCwF9ZnJm      0
49452724  zsA2dnzCR5  2012-05-10 00:55:42.0   Voice  zsA2dnzCR5     14
49452725  xxbbz32oIL  2012-05-10 00:55:51.0     sms  xxbbz32oIL      0
49452726  zbVRn1hiwe  2012-05-10 00:55:53.0     sms  zbVRn1hiwe      0
49452727  yPq8TPd7WC  2012-05-10 00:57:11.0     sms  yPq8TPd7WC     25
49452728  zqHx55Evcc  2012-05-10 00:59:04.0     sms  zqHx55Evcc      0

In [37]:
moringas.shape

(49452729, 5)

In [38]:
moringas.columns

Index(['cell_id', 'date_time', 'product', 'site_id', 'value'], dtype='object')

In [39]:
#checks which columns if any has missing values
df.columns[df.isnull().any()]

Index([], dtype='object')

In [40]:
#dropping all rows that have a value = 0
moringas.drop(moringas.loc[moringas['value']==0].index, inplace=True)

In [41]:
moringas.head()

       cell_id              date_time product     site_id  value
2   /u0FSD+ahi  2012-05-06 23:05:41.0     sms  /u0FSD+ahi     25
3   +cNeJzsTp3  2012-05-06 23:05:42.0   Voice  +cNeJzsTp3     56
4   051KhYDCpv  2012-05-06 23:06:29.0   Voice  051KhYDCpv     14
13  2dmu2Iy1CX  2012-05-06 23:09:16.0     sms  2dmu2Iy1CX     25
16  ++ctND+jGD  2012-05-06 23:09:54.0   Voice  ++ctND+jGD     44

In [42]:
moringas.shape

(25618916, 5)

In [43]:
moringas.dtypes

cell_id      object
date_time    object
product      object
site_id      object
value         int64
dtype: object

In [49]:
#convert the date time column to datetime datatype
moringas.date_time = pd.to_datetime(moringas.date_time)

In [50]:
#splitting date_time to date and time
moringas['date'] = [d.date() for d in moringas.date_time]

In [51]:
moringas.columns

Index(['cell_id', 'date_time', 'product', 'site_id', 'value', 'date'], dtype='object')

In [52]:
moringas['time'] = [d.time() for d in moringas.date_time]

In [53]:
moringas.columns

Index(['cell_id', 'date_time', 'product', 'site_id', 'value', 'date', 'time'], dtype='object')

In [55]:
mergedsample = df.merge(moringas, how='inner', left_on='cell_id', right_on='site_id')
mergedsample

,cities,status,localisation,region,cell_id_x,site_id_x,cell_id_y,date_time,product,site_id_y,value,date,time
0,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,4261f660ef,2012-05-07 00:00:02,Voice,69bdfc69fd,80,2012-05-07,00:00:02
1,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:00:02,Voice,69bdfc69fd,22,2012-05-07,00:00:02
2,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:00:46,Voice,69bdfc69fd,18,2012-05-07,00:00:46
3,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:01:04,Voice,69bdfc69fd,36,2012-05-07,00:01:04
4,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:02:11,Voice,69bdfc69fd,12,2012-05-07,00:02:11
5,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:02:20,Voice,69bdfc69fd,12,2012-05-07,00:02:20
6,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:02:22,Voice,69bdfc69fd,10,2012-05-07,00:02:22
7,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:02:22,Voice,69bdfc69fd,10,2012-05-07,00:02:22
8,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,87d9d44f76,2012-05-07 00:02:57,Voice,69bdfc69fd,76,2012-05-07,00:02:57
9,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:04:04,Voice,69bdfc69fd,91,2012-05-07,00:04:04
10,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:04:11,Voice,69bdfc69fd,72,2012-05-07,00:04:11
11,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,4261f660ef,2012-05-07 00:04:38,Voice,69bdfc69fd,5,2012-05-07,00:04:38
12,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,4261f660ef,2012-05-07 00:05:04,Voice,69bdfc69fd,19,2012-05-07,00:05:04
13,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:05:15,Voice,69bdfc69fd,140,2012-05-07,00:05:15
14,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,4261f660ef,2012-05-07 00:05:36,Voice,69bdfc69fd,34,2012-05-07,00:05:36
15,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:05:46,Voice,69bdfc69fd,57,2012-05-07,00:05:46
16,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,e25fdac0bc,2012-05-07 00:05:52,Voice,69bdfc69fd,30,2012-05-07,00:05:52
17,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,440656f6dd,2012-05-07 00:05:55,Voice,69bdfc69fd,25,2012-05-07,00:05:55
18,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:06:04,Voice,69bdfc69fd,44,2012-05-07,00:06:04
19,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:06:20,Voice,69bdfc69fd,202,2012-05-07,00:06:20
20,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,440656f6dd,2012-05-07 00:06:51,Voice,69bdfc69fd,124,2012-05-07,00:06:51
21,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,4261f660ef,2012-05-07 00:08:29,Voice,69bdfc69fd,41,2012-05-07,00:08:29
22,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:08:30,Voice,69bdfc69fd,98,2012-05-07,00:08:30
23,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:08:46,Voice,69bdfc69fd,120,2012-05-07,00:08:46
24,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:09:04,Voice,69bdfc69fd,104,2012-05-07,00:09:04
25,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 00:09:37,Voice,69bdfc69fd,1,2012-05-07,00:09:37
26,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:09:46,Voice,69bdfc69fd,32,2012-05-07,00:09:46
27,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:10:06,Voice,69bdfc69fd,37,2012-05-07,00:10:06
28,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,440656f6dd,2012-05-07 00:11:10,Voice,69bdfc69fd,35,2012-05-07,00:11:10
29,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 00:11:33,Voice,69bdfc69fd,38,2012-05-07,00:11:33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9047915,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:47:23,Voice,3ae1708153,54,2012-05-09,23:47:23
9047916,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,244322c7dd,2012-05-09 23:47:53,Voice,3ae1708153,227,2012-05-09,23:47:53
9047917,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:48:11,sms,3ae1708153,25,2012-05-09,23:48:11
9047918,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:48:40,Voice,3ae1708153,71,2012-05-09,23:48:40
9047919,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:48:54,sms,3ae1708153,25,2012-05-09,23:48:54
9047920,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:50:09,Voice,3ae1708153,60,2012-05-09,23:50:09
9047921,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:50:40,Voice,3ae1708153,48,2012-05-09,23:50:40
9047922,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:51:12,Voice,3ae1708153,84,2012-05-09,23:51:12
9047923,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:51:23,sms,3ae1708153,25,2012-05-09,23:51:23
9047924,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:51:23,sms,3ae1708153,25,2012-05-09,23:51:23
9047925,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:51:29,sms,3ae1708153,25,2012-05-09,23:51:29
9047926,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:51:38,Voice,3ae1708153,21,2012-05-09,23:51:38
9047927,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,4348844796,2012-05-09 23:53:18,Voice,3ae1708153,12,2012-05-09,23:53:18
9047928,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:53:28,Voice,3ae1708153,104,2012-05-09,23:53:28
9047929,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:53:34,Voice,3ae1708153,13,2012-05-09,23:53:34
9047930,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:53:57,Voice,3ae1708153,143,2012-05-09,23:53:57
9047931,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,4d38824e5a,2012-05-09 23:54:07,Voice,3ae1708153,240,2012-05-09,23:54:07
9047932,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,4348844796,2012-05-09 23:54:17,Voice,3ae1708153,65,2012-05-09,23:54:17
9047933,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:56:14,Voice,3ae1708153,7,2012-05-09,23:56:14
9047934,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:56:26,Voice,3ae1708153,23,2012-05-09,23:56:26
9047935,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,4348844796,2012-05-09 23:56:54,Voice,3ae1708153,3,2012-05-09,23:56:54
9047936,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:57:31,Voice,3ae1708153,12,2012-05-09,23:57:31
9047937,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:57:42,Voice,3ae1708153,36,2012-05-09,23:57:42
9047938,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,4348844796,2012-05-09 23:57:52,Voice,3ae1708153,51,2012-05-09,23:57:52
9047939,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:57:59,Voice,3ae1708153,9,2012-05-09,23:57:59
9047940,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:58:14,Voice,3ae1708153,228,2012-05-09,23:58:14
9047941,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,e02ac3afbd,2012-05-09 23:58:41,Voice,3ae1708153,2,2012-05-09,23:58:41
9047942,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:58:43,Voice,3ae1708153,17,2012-05-09,23:58:43
9047943,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,93d38fc386,2012-05-09 23:59:07,Voice,3ae1708153,45,2012-05-09,23:59:07
9047944,ZUENOULA,In Service,INTERIEUR,MARAHOUE,3ae1708153,f91ed8d2e9,db03a198b7,2012-05-09 23:59:12,Voice,3ae1708153,10,2012-05-09,23:59:12

In [56]:
#Analysis of the merged data
#product usage for all days
mergedsample.groupby(['date', 'product'])['product'].count().sort_values(ascending = False)

date        product
2012-05-07  Voice      2980130
2012-05-09  Voice      2877173
2012-05-08  Voice      2771493
            sms         116539
2012-05-09  sms         105611
2012-05-07  sms         102892
            data         47701
2012-05-09  data         46406
Name: product, dtype: int64

In [108]:
x = mergedsample.groupby(['cities', 'product'])['product'].count().sort_values(ascending = False)
x

cities         product
BOUAKE         Voice      1115872
SAN-PEDRO      Voice       666323
DALOA          Voice       420432
ABOBO          Voice       362897
MAN            Voice       360029
DIVO           Voice       347722
BOUNA          Voice       347008
GRAND-BASSAM   Voice       252949
ASSINIE        Voice       242145
DABOU          Voice       236680
COCODY         Voice       209612
AGNIBILEKRO    Voice       196619
ADZOPE         Voice       193674
DAOUKRO        Voice       170168
GAGNOA         Voice       156245
DABAKALA       Voice       146057
ABOISSO        data        140796
BONOUA         Voice       138267
DJEMISSIKRO    Voice       135146
BOUNDIALI      Voice       120258
YAMOUSSOUKRO   Voice       117134
ABOISSO        Voice       112248
DJEBONOUA      Voice       107054
BOUAFLE        Voice       100125
N'ZIKRO        Voice        96842
GRAND BEREBY   Voice        95494
NOE            Voice        94688
ATTINGUIE      Voice        94086
MEADJI         Voice        91648
DIEGONEFLA     Voice        85106
                           ...
AKRADJO        Voice            2
BOZI           Voice            2
BIN HOUNIEN    Voice            2
DIABO          sms              2
BOROTOUKRO     Voice            2
BLOLEQUIN      Voice            2
MINORE         sms              2
TANKESSE       Voice            2
BOLI           Voice            2
MANKONO        Voice            2
KRIKOREA       Voice            1
DAGADJI        sms              1
VAVOUA         sms              1
NOUAMOU        sms              1
TOUPAH         sms              1
KOUN-FAO       sms              1
ZIKISSO        Voice            1
RUBINO         sms              1
KRINJABO       sms              1
TOROGUHE       Voice            1
GONATE         Voice            1
OKROUYO        Voice            1
BECEDIBRIGNAN  Voice            1
BINGERVILLE    sms              1
GAZIBOUO       Voice            1
BONDOUKOU      sms              1
MAHAPLEU       Voice            1
SINGROBO       Voice            1
DOKE           Voice            1
ATTECOUBE      sms              1
Name: product, Length: 233, dtype: int64

In [57]:
mergedsample.groupby(['region', 'product'])['product'].count().sort_values(ascending = False)

region             product
LAGUNE             Voice      1860021
VALLEE DU BANDAMA  Voice      1410698
BAS SASSANDRA      Voice       874943
SUD COMOE          Voice       831279
HAUT SASSANDRA     Voice       460047
SUD BANDAMA        Voice       410068
ZANZAN             Voice       365732
18 MONTAGNES       Voice       360039
NZI COMOE          Voice       295319
FROMAGER           Voice       285147
MARAHOUE           Voice       277041
AGNEBY             Voice       266768
SAVANE             Voice       259856
MOYEN COMOE        Voice       256538
LACS               Voice       210924
SUD COMOE          data         94107
WORODOUGOU         Voice        85067
LAGUNE             sms          78300
MOYEN CAVALLY      Voice        67609
VALLEE DU BANDAMA  sms          63985
DENGUELE           Voice        51698
SUD COMOE          sms          30747
BAS SASSANDRA      sms          25481
HAUT SASSANDRA     sms          18799
SUD BANDAMA        sms          16366
MARAHOUE           sms          14605
NZI COMOE          sms          14342
18 MONTAGNES       sms           9658
AGNEBY             sms           9422
ZANZAN             sms           9234
FROMAGER           sms           8750
SAVANE             sms           7490
MOYEN COMOE        sms           7059
LACS               sms           4596
WORODOUGOU         sms           3268
MOYEN CAVALLY      sms           1495
DENGUELE           sms           1445
BAFING             Voice            2
Name: product, dtype: int64

In [67]:
mergedsample['date'] =  pd.to_datetime(mergedsample['date'],format='%Y-%m-%d', errors = 'ignore')

In [68]:
mergedsample['time'] =  pd.to_datetime(mergedsample['time'],format='%H:%M:%S:%f', errors = 'ignore')

In [69]:
mergedsample.rename(columns= {'date_time':'datetime'}, inplace = True)

In [70]:
mergedsample.columns

Index(['cities', 'status', 'localisation', 'region', 'cell_id_x', 'site_id_x',
       'cell_id_y', 'datetime', 'product', 'site_id_y', 'value', 'date',
       'time'],
      dtype='object')

In [72]:
import datetime as dt

In [147]:
workinghrs.groupby('cities')['cities'].count().sort_values(ascending = False)

cities
BOUAKE           560598
SAN-PEDRO        307811
DALOA            196877
MAN              170315
ABOBO            162163
DIVO             160311
BOUNA            157460
GRAND-BASSAM     128194
DABOU            120041
ASSINIE          117487
ABOISSO          109606
AGNIBILEKRO      100485
COCODY            96774
ADZOPE            95083
DJEMISSIKRO       83732
DAOUKRO           76642
BONOUA            74747
DABAKALA          72090
GAGNOA            61222
BOUNDIALI         60810
DJEBONOUA         57150
BOUAFLE           51704
YAMOUSSOUKRO      48300
N'ZIKRO           44271
BONON             42692
GRAND BEREBY      42199
NOE               41582
SEGUELA           40680
ATTINGUIE         40399
DIEGONEFLA        38801
                  ...
KRINJABO              7
DIDIEVI               7
BOCANDA               6
TIASSALE              6
DIABO                 5
RUBINO                5
BANGOLO               5
TABAGNE               4
BONDOUKOU             4
GOHITAFLA             4
CECHI                 3
GONATE                3
AGOU                  3
KOREA                 2
ADJAMENE              2
BOZI                  2
BIN HOUNIEN           2
DIVO PALMCI           2
OUELLE                2
DOKE                  1
GAZIBOUO              1
BECEDIBRIGNAN         1
AKRADJO               1
TIEMELEKRO            1
TOROGUHE              1
TIAPOUM               1
NOUAMOU               1
DAGADJI               1
KRIKOREA              1
BOROTOUKRO            1
Name: cities, Length: 122, dtype: int64

In [75]:
#working hrs between 8 and 5

import datetime

workinghrs =mergedsample[(mergedsample.datetime.dt.time >= datetime.time(8)) & (mergedsample.datetime.dt.time <= datetime.time(17))]

workinghrs.head()

#mergedsample[(mergedsample.datetime.dt.time >= datetime.time(8)) & (mergedsample.datetime.dt.time <= datetime.time(17))]

,cities,status,localisation,region,cell_id_x,site_id_x,cell_id_y,datetime,product,site_id_y,value,date,time
1503,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:05,Voice,69bdfc69fd,807,2012-05-07,08:00:05
1504,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 08:00:06,Voice,69bdfc69fd,300,2012-05-07,08:00:06
1505,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:07,Voice,69bdfc69fd,120,2012-05-07,08:00:07
1506,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 08:00:08,Voice,69bdfc69fd,94,2012-05-07,08:00:08
1507,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:08,Voice,69bdfc69fd,15,2012-05-07,08:00:08

In [76]:
workinghrs.groupby('cities')['cities'].count().sort_values(ascending = False)

cities
BOUAKE           625077
SAN-PEDRO        345754
DALOA            222048
MAN              187717
ABOBO            182984
DIVO             181058
BOUNA            178039
GRAND-BASSAM     144719
DABOU            134275
ASSINIE          130891
AGNIBILEKRO      110500
COCODY           109344
ADZOPE           106197
ABOISSO           99367
DJEMISSIKRO       92346
DAOUKRO           87036
BONOUA            83158
DABAKALA          81004
GAGNOA            72917
BOUNDIALI         67933
DJEBONOUA         64078
BOUAFLE           57657
YAMOUSSOUKRO      56077
N'ZIKRO           50000
GRAND BEREBY      48857
BONON             48068
NOE               47021
ATTINGUIE         45729
SEGUELA           45608
MEADJI            44112
                  ...
BOCANDA               6
BANGOLO               5
TABAGNE               5
DIABO                 5
RUBINO                5
GOHITAFLA             4
RAVIART               4
GONATE                3
AGOU                  3
CECHI                 3
BOZI                  2
KOREA                 2
DIVO PALMCI           2
BLOLEQUIN             2
OUELLE                2
ADJAMENE              2
BIN HOUNIEN           2
TOROGUHE              1
NOUAMOU               1
KOUN-FAO              1
BOROTOUKRO            1
TANKESSE              1
DOKE                  1
TIEMELEKRO            1
AKRADJO               1
GAZIBOUO              1
KRIKOREA              1
DAGADJI               1
BECEDIBRIGNAN         1
TIAPOUM               1
Name: cities, Length: 126, dtype: int64

In [80]:
#not working hours between 5am and 8am
nworkinghrs =mergedsample[(mergedsample.datetime.dt.time <= datetime.time(17)) & (mergedsample.datetime.dt.time >= datetime.time(8))]

nworkinghrs.head()

,cities,status,localisation,region,cell_id_x,site_id_x,cell_id_y,datetime,product,site_id_y,value,date,time
1503,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:05,Voice,69bdfc69fd,807,2012-05-07,08:00:05
1504,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 08:00:06,Voice,69bdfc69fd,300,2012-05-07,08:00:06
1505,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:07,Voice,69bdfc69fd,120,2012-05-07,08:00:07
1506,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,f76d889a00,2012-05-07 08:00:08,Voice,69bdfc69fd,94,2012-05-07,08:00:08
1507,ASSINIE,In Service,INTERIEUR,SUD COMOE,69bdfc69fd,8a1e6ce31f,d250ec4e98,2012-05-07 08:00:08,Voice,69bdfc69fd,15,2012-05-07,08:00:08

In [81]:
nworkinghrs.groupby('cities')['cities'].count().sort_values(ascending = False)

cities
BOUAKE           625077
SAN-PEDRO        345754
DALOA            222048
MAN              187717
ABOBO            182984
DIVO             181058
BOUNA            178039
GRAND-BASSAM     144719
DABOU            134275
ASSINIE          130891
AGNIBILEKRO      110500
COCODY           109344
ADZOPE           106197
ABOISSO           99367
DJEMISSIKRO       92346
DAOUKRO           87036
BONOUA            83158
DABAKALA          81004
GAGNOA            72917
BOUNDIALI         67933
DJEBONOUA         64078
BOUAFLE           57657
YAMOUSSOUKRO      56077
N'ZIKRO           50000
GRAND BEREBY      48857
BONON             48068
NOE               47021
ATTINGUIE         45729
SEGUELA           45608
MEADJI            44112
                  ...
BOCANDA               6
BANGOLO               5
TABAGNE               5
DIABO                 5
RUBINO                5
GOHITAFLA             4
RAVIART               4
GONATE                3
AGOU                  3
CECHI                 3
BOZI                  2
KOREA                 2
DIVO PALMCI           2
BLOLEQUIN             2
OUELLE                2
ADJAMENE              2
BIN HOUNIEN           2
TOROGUHE              1
NOUAMOU               1
KOUN-FAO              1
BOROTOUKRO            1
TANKESSE              1
DOKE                  1
TIEMELEKRO            1
AKRADJO               1
GAZIBOUO              1
KRIKOREA              1
DAGADJI               1
BECEDIBRIGNAN         1
TIAPOUM               1
Name: cities, Length: 126, dtype: int64

In [83]:
#sort products by values so see those that are making more for the company
mergedsample.groupby('product')['product'].count().sort_values(ascending = False)

product
Voice    8628796
sms       325042
data       94107
Name: product, dtype: int64